var comment = {
		error : "오류가 발생됬습니다.\n관리자에게 문의하세요.",
		error_image_file_include_korean :"이미지 파일에 한글이 포함되어있습니다.",
		auth_error : "권한이 없습니다.",
		cancel : "취소되었습니다.",
		insert_number : "숫자를 입력하세요.",
		insert_id : "아이디를 입력하세요.",
		insert_password : "비밀번호를 입력하세요",
		download : "다운로드",
		insert : "등록",
		update : "수정",
		
		isInsert : "등록하시겠습니까?",
		isUpdate : "수정하시겠습니까?",
		isUpdate2 : "변경된 내용을 저장 하시겠습니까?",
		isDelete : "삭제하시겠습니까?",
		isAdd : "추가하시겠습니까?",
		isExcelDownload : "엑셀표를 다운로드 받으시겠습니까?",
		isSend : "발송하시겠습니까?",
		isCancel : "취소하시겠습니까?",
		isSave : "저장 하시겠습니까?",
    	isSave2 : "입력된 정보를 저장 하시겠습니까?",
		isChange : "변경하시겠습니까?",

		select_member : "멤버 종류를 선택하세요.",
		select_search_list : "검색종류를 선택하세요.",
		select_year : "년도를 선택하세요.",
		select_product : "상품종류를 선택하세요.",
		select_item : "아이템종류를 선택하세요.",
		select_start_date : "시작일을 선택하세요.",
		select_end_date : "종료일을 선택하세요.",
		select_search_date : "검색일을 선택하세요.",
		select_excel_file : "엑셀파일을 선택하세요.",
		
		check_item : "항목을 체크하세요.",
		not_update_item : "변경될 항목이 없습니다.",
		
		blank_list : "목록이 없습니다.",
    	blank_lecture_list : "수강 이력이 없습니다.",
		blank_list2 : "검색 결과가 없습니다.",
		blank_result : "결과가 없습니다.",
		blank_search_result : "검색된 결과가 없습니다.",
		blank_check_all : "체크된 항목이 없습니다. 전체체크 하세요.",
		blank_check : "체크된 값이 없습니다.",
		blank_login_check : "아이디 또는 비밀번호를 확인해 주세요.",
		black_login_password_check : "가입 정보가 일치하지 않습니다. 아이디 또는 이메일 주소를 확인해 주세요. ",
		success_withdrawral : "회원탈퇴가 정상적으로 처리되었습니다.",
		success_process : "완료됬습니다.",
		success_delete : "삭제되었습니다.",
		success_cancel : "취소되었습니다.",
		success_update : "수정됬습니다.",

		load_data : "데이타를 불러오는중..",

    	input_academy_group : "그룹명을 선택하세요.",
		input_academy_name : "학원명을 입력해주세요.",
        input_academy_directorname : "학원원장명을 입력해주세요.",
		input_academy_phone1 : "핸드폰번호 입력해주세요.",
		input_academy_phone2 : "핸드폰번호 입력해주세요.",
		input_academy_phone3 : "핸드폰번호 입력해주세요.",
        input_academy_address : "학원주소를 입력해주세요",
		input_academy_fax : "팩스번호를 입력해주세요.",

    	input_member_type : "직원타입을 선택해주세요.",
    	input_member_posiotion:"직책을 선택해주세요.",
    	input_member_academy:"소속부서를 선택해주세요.",
    	input_member_team:"소속팀을 선택해주세요.",
		input_member_name : "직원명을 입력해주세요.",
    	input_mother_name : "부모님(모)명을 입력해주세요.",
		input_member_phone1 : "핸드폰번호 입력해주세요.",
    	input_member_phone2 : "핸드폰번호 입력해주세요.",
    	input_member_phone3 : "핸드폰번호 입력해주세요.",
		input_member_startDate : "생년월일을 입력해주세요.",
		input_member_tel1 : "전화번호를 입력해주세요.",
		input_member_tel2 : "전화번호를 입력해주세요",
		input_member_tel3 : "전화번호를 입력해주세요",
		input_mother_tel1 : "부모님(모) 전화번호를 입력해주세요.",
		input_mother_tel2 : "부모님(모)전화번호를 입력해주세요",
		input_mother_tel3 : "부모님(모)전화번호를 입력해주세요",
    	input_member_address : "주소를 입력해주세요.",
    	input_member_email : "이메일주소를 입력해주세요.",
   		input_member_startSearchDate : "성범죄경력조회 확인일자를 선택해주세요.",
    	input_member_startSearchDate2: "교육청 강사등록일자를 선택해주세요.",

    	input_student_grade:"학생의 학년을 선택해주세요.",
		input_student_name : "학생 이름을 입력하세요.",
    	input_school_name : "학교이름을 입력하세요.",

		payment_error : "결제결과 에러가 발생되었습니다.",
		select_installMent : "할부개월을 선택해주세요.",
		select_cash_receipt_type : "현금영수증을 선택해주세요.",
		select_consult_type : "상담유형을 선택해주세요.",

		file_name_not_allow_korean : "파일명이 한글입니다. 영문으로 바꿔주세요.",
		file_extension_not_allow : "파일확장자는 'JPG, GIF'만 가능합니다.",
		file_size_not_allow_300kb : "첨부된 파일크기가 큽니다. 300KB 이미지만 첨부 가능합니다.",

		not_attend_log : "출결이력이 없습니다.",
		not_lecture_log : "수강이력이 없습니다",
    	not_consult_log_three : "최근 상담 내역이 없습니다.",
		not_consult_log : "상담 내역이 없습니다.",
		search_input_student_name : "학생 이름을 입력 후 검색해주세요.",
        search_input_id_name : "이름을 입력해주세요.",

		success_update : "수정됬습니다",
		send_email : "입력하신 이메일 주소로 아이디를 전송 하였습니다.",
		blank_send_email : "이름 또는 이메일 주소를 확인해 주세요.",

}

